#include "/Engine/Public/Platform.ush"

RWTexture2D<float4> RWOutputSurface;
float Total;

[numthreads(THREADGROUP_SIZE_X, THREADGROUP_SIZE_Y, THREADGROUP_SIZE_Z)]
void MainCS(
	uint3 GroupId : SV_GroupID,
	uint3 DispatchThreadId : SV_DispatchThreadID,
	uint3 GroupThreadId : SV_GroupThreadID)
	{
		RWOutputSurface[DispatchThreadId.xy] = float4((DispatchThreadId.x/Total),(DispatchThreadId.y/Total),0,1);
	}