#include "/Engine/Public/Platform.ush"

Texture2D InputTex;
RWTexture2D<float4> RWOutputSurface;
float Total;

[numthreads(THREADGROUP_SIZE_X, THREADGROUP_SIZE_Y, THREADGROUP_SIZE_Z)]
void MainCS(
	uint3 GroupId : SV_GroupID,
	uint3 DispatchThreadId : SV_DispatchThreadID,
	uint3 GroupThreadId : SV_GroupThreadID)
	{
	//float3 SampleColor = InTexture.Sample(Sampler, DispatchThreadId.xy).rgb;
		RWOutputSurface[DispatchThreadId.xy] = InputTex[DispatchThreadId.xy]*100;
	}